# Generated by Django 3.0.6 on 2020-09-18 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitty',
            name='person1_email',
            field=models.CharField(default='lakshya', max_length=100),
            preserve_default=False,
        ),
    ]
