# Generated by Django 3.0.6 on 2020-09-18 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0002_kitty_person1_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_person', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('split_equ_all', models.BooleanField()),
                ('split_diff', models.BooleanField()),
                ('exp_name', models.CharField(max_length=100)),
                ('date', models.DateField()),
            ],
        ),
    ]
