# Generated by Django 3.0.6 on 2020-09-18 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0003_expense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='split_diff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='expense',
            name='split_equ_all',
            field=models.BooleanField(default=True),
        ),
    ]
