# Generated by Django 3.0.6 on 2020-09-18 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0004_auto_20200918_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitty',
            name='person3',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
