# Generated by Django 3.0.6 on 2020-09-18 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0006_remove_kitty_person3'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitty',
            name='person3',
            field=models.CharField(default='lpra', max_length=100),
            preserve_default=False,
        ),
    ]
